package com.example.Store;

public class Product {
    // all the product information
    String productId; // unique ID that will be generated by the system UUID
    // SQL Post
    String title;
    String brand;
    Double price;
    // details of the product weight dimensions, mfg
}
